export const STARTER_DATA = {
  settings: {
    restaurant_name: "Harbor Table",
    currency_symbol: "$",
  },
  categories: [
    { id: 1, name: "Starters", display_order: 1 },
    { id: 2, name: "Mains", display_order: 2 },
    { id: 3, name: "Drinks", display_order: 3 },
  ],
  items: [
    {
      id: 1,
      category_id: 1,
      name: "Crispy Calamari",
      description: "Lightly fried squid with lemon aioli.",
      price: 12.5,
      image_url: "",
      is_available: true,
      tags: ["Spicy"],
      prep_time: 12,
    },
    {
      id: 2,
      category_id: 1,
      name: "Garden Hummus Plate",
      description: "Chickpea spread, warm pita, and raw vegetables.",
      price: 9,
      image_url: "",
      is_available: true,
      tags: ["Vegetarian", "Gluten-Free"],
      prep_time: 8,
    },
    {
      id: 3,
      category_id: 2,
      name: "Herb Roast Chicken",
      description: "Half chicken, pan juices, roasted potatoes.",
      price: 22,
      image_url: "",
      is_available: true,
      tags: ["Gluten-Free"],
      prep_time: 25,
    },
    {
      id: 4,
      category_id: 2,
      name: "Mushroom Risotto",
      description: "Arborio rice, wild mushrooms, parmesan.",
      price: 18.5,
      image_url: "",
      is_available: true,
      tags: ["Vegetarian"],
      prep_time: 20,
    },
    {
      id: 5,
      category_id: 3,
      name: "House Lemonade",
      description: "Fresh lemon, mint, sparkling water.",
      price: 4.5,
      image_url: "",
      is_available: true,
      tags: ["Vegetarian", "Gluten-Free"],
      prep_time: 3,
    },
    {
      id: 6,
      category_id: 3,
      name: "Chili Mango Cooler",
      description: "Mango puree with a gentle chili rim.",
      price: 6,
      image_url: "",
      is_available: true,
      tags: ["Spicy", "Vegetarian"],
      prep_time: 4,
    },
  ],
};

export const ALL_TAGS = ["Gluten-Free", "Vegetarian", "Spicy"];
